source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# Use Unicorn as the app server
gem 'unicorn'
# Use Taperole for deployment
# gem 'taperole'

group :development, :test do
  # Use rspec as the testing framework
  gem 'rspec-rails'
  # Use factory girl for fixtures
  gem 'factory_girl_rails'
  # Use database cleaner for cleaning the database
  gem 'database_cleaner'
  # Call 'binding.pry' anywhere in the code to stop execution and get a debugger console
  gem 'pry-byebug'
  # Use awesome-print to pretty print Ruby objects
  gem 'awesome_print'
  # Use rubocop for linting
  gem 'rubocop'
  # Use shouldamatchers to test associations and validations
  gem 'shoulda-matchers'
  # Use to integrate Code Climate and Travis
  gem "codeclimate-test-reporter", require: nil
end

group :development do
  gem 'listen', '~> 3.0.5'
  # Use letter_opener to view emails in browser rather than send
  # gem 'letter_opener'
  # Use better_errors to get a full stack trace
  gem "better_errors"
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
